config/routes.rb
Rails.application.routes.draw do

  resources :quiz_sessions do
    member do
      get 'start'
    end
    resources :answers, only: [:create]
  end

  resources :answers, only: [:create]

  resources :questions do
    member do
      patch :toggle_status
    end
  end

  resources :quizzes do
    resources :questions
    resources :quiz_sessions
    member do
      post :add_questions
    end
  end

  devise_for :users

  authenticated :user do
    root 'quizzes#index', as: :authenticated_root
  end

  root "quizzes#index"

  resources :entries

  resources :children do
    resources :entries, only: [:create, :destroy, :new, :show, :edit, :update]
  end

  resources :users do
    resources :children
  end
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")

end

app/models/quiz.rb
class Quiz < ApplicationRecord
  has_many :quiz_questions, dependent: :destroy
  has_many :questions, through: :quiz_questions
  has_many :quiz_sessions, dependent: :destroy

  accepts_nested_attributes_for :questions, allow_destroy: true

  enum status: { draft: 'draft', active: 'active', another_status: 'another_status' }
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  after_action :verify_authorized, except: :index

  def index
    @quizzes = policy_scope(Quiz)

    if current_user && current_user.admin?
      render 'index'
    else
      render 'user_index'
    end
  end

  def show
    authorize @quiz

    if current_user && current_user.admin?
      render 'show'
    else
      render 'user_show'
    end
  end

  def new
    @quiz = Quiz.new
    authorize @quiz
  end

  def create
    @quiz = Quiz.new(quiz_params)
      if @quiz.save
        redirect_to @quiz, notice: 'Quiz was successfully created.'
      else
        render :new
      end
  end

  def edit
  end

  def update
    @quiz.update(quiz_params)
    redirect_to @quiz, notice: 'Quiz was successfully updated.'
  end

  def destroy
    @quiz.destroy
    redirect_to quizzes_url, notice: 'Quiz was successfully destroyed.'
  end

  def add_questions
    @quiz = Quiz.find(params[:id])
    @quiz.question_ids = params[:quiz][:question_ids]

    if @quiz.save
      # Handle success (perhaps redirect or re-render the component to show the updated list of questions)
    else
      # Handle failure
    end
  end


  private

  def set_quiz
    @quiz = Quiz.find(params[:id])
  end

  def quiz_params
    params.require(:quiz).permit(:title, :description, :total_questions, :active, :category, :status)
  end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/_form.html.erb
<%= form_with(model: @quiz, local: true, class: "space-y-6") do |form| %>

  <% if @quiz.errors.any? %>
    <div id="error_explanation" class="p-4 mb-4 bg-red-100 text-red-700 border border-red-400 rounded">
      <h2 class="font-semibold"><%= pluralize(@quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul class="list-disc list-inside">
        <% @quiz.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, class: "block text-sm font-medium text-gray-700" %>
    <%= form.text_field :title, id: :quiz_title, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
  </div>

  <div class="field">
    <%= form.label :description, class: "block text-sm font-medium text-gray-700" %>
    <%= form.text_area :description, id: :quiz_description, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50", rows: 4 %>
  </div>

  <div class="field">
    <%= form.label :status, class: "block text-sm font-medium text-gray-700" %>
    <%= form.select :status, Quiz.statuses.keys.map { |status| [status.titleize, status] }, {}, { id: :quiz_status, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" } %>
  </div>

  <div class="actions">
    <%= form.submit class: "inline-flex items-center px-4 py-2 bg-indigo-600 border border-transparent rounded-md font-semibold text-xs uppercase tracking-widest hover:bg-indigo-500 focus:outline-none focus:border-indigo-700 focus:ring focus:ring-indigo-200 active:bg-indigo-600 disabled:opacity-25 transition" %>
  </div>
<% end %>

app/views/quizzes/_quiz.html.erb
<div id="<%= dom_id quiz %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= quiz.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= quiz.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%#= child.user_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Birthdate:</strong>
    <%#= child.birthdate %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Gender:</strong>
    <%#= child.gender %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Profile:</strong>
    <%#= child.profile %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show quiz", quiz, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%#= link_to "Edit this child", edit_child_path(child), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/quizzes/edit.html.erb
<div>
  <h1 class="font-bold text-4xl">Edit Quiz</h1>
</div>
<%= render 'form', quiz: @quiz, show_actions: true %>

app/views/quizzes/index.html.erb
<div>
  <h2 class="font-bold text-4xl">Quizzes (Admin View)</h2>
 
  <div class="overflow-x-auto">
    <table class="table table-xs">
      <thead>
        <tr>
          <th style="width: 20px;"></th> 
          <th style="width: 250px;">Title</th> 
          <th style="width: 30px;">Status</th>
          <th style="width: 350px;">Description</th>
          <th style="width: 30px;">Action</th>
        </tr>
      </thead> 
      <tbody>
        <% @quizzes.each do |q| %>
          <tr>
            <th>1</th> 
            <td><%= link_to q.title, quiz_path(q) %></td></td> 
            <td><%= q.active? %></td>
            <td><%= q.description %></td> 
            <td>
              <%= link_to "Delete", quiz_path(q), data: { turbo_method: :delete}, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded"  %>
            </td>
          </tr>
        <% end %>
      </tbody> 
    </table>
  </div>

  <div class="mt-5">
    <%= link_to "New Quiz", new_quiz_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
  </div>
</div>

app/views/quizzes/new.html.erb
<%= render 'form' %>

app/views/quizzes/show.html.erb
<div class="max-w-5xl mx-auto py-10 px-4 sm:px-6 lg:px-8">
  <div class="mb-10">
    <h1 class="text-4xl font-extrabold text-gray-900 mb-1"><%= @quiz.title %></h1>
    <p class="text-lg text-gray-500"><%= @quiz.description %></p>
  </div> 
  <div> 
    <%= link_to 'Start Quiz', new_quiz_quiz_session_path(quiz_id: @quiz.id) %>
  </div> <br>

  <div id="questions" class="mb-8">
    <%= turbo_frame_tag "questions_list" do %>
      <div class="divide-y divide-gray-200">
        <%= render @quiz.questions %>
      </div>
    <% end %>
  </div>

  <div class="mt-10 bg-white p-6 shadow-lg rounded-lg">
    <h3 class="text-lg leading-6 font-medium text-gray-900 mb-4">Add a new question</h3>

    <div class="mt-10 bg-white p-6 shadow-lg rounded-lg">
      <h3 class="text-lg leading-6 font-medium text-gray-900 mb-4">Add Existing Questions to Quiz</h3>
      <%= turbo_frame_tag "add_questions" do %>
        <%= form_with url: add_questions_quiz_path(@quiz), method: :post, data: { turbo_frame: "add_questions" } do |form| %>
          <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            <% Question.all.each do |question| %>
              <div class="flex items-center">
                <%= check_box_tag "quiz[question_ids][]", question.id, @quiz.questions.include?(question), id: dom_id(question) %>
                <%= label_tag dom_id(question), question.text.to_plain_text.truncate(50), class: "ml-2 block text-sm font-medium text-gray-700" %>

              </div>
            <% end %>
          </div>
          <%= form.submit "Add Selected Questions", class: "btn btn-primary mt-4" %>
        <% end %>
      <% end %>
    </div>

  </div>
</div>

app/views/quizzes/user_index.html.erb
<div class="mx-auto md:w-2/3 w-full ">
    <h2 class="font-bold text-3xl">Quizzes</h2>
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="inline-block ml-2">
    <%#= link_to 'Add a child', new_child_path , class:'mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium' %>
  </div>

  <% @quizzes.each do |quiz|  %>
    <div class="container mx-auto py-4">
      <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-3 2xl:grid-cols-4 gap-6">
        <!-- Card -->
        <div class="card w-50 bg-base-100 shadow-xl">
          <figure><img src="https://daisyui.com/images/stock/photo-1606107557195-0e29a4b5b4aa.jpg" alt="Shoes" /> </figure>
            <div class="card-body">
              <h2 class="card-title">
                <%= link_to quiz.title, quiz_path(quiz), class:'' %>
              </h2>
            </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/quizzes/user_show.html.erb
<div class="max-w-5xl mx-auto py-10 px-4 sm:px-6 lg:px-8">
  <div class="mb-10">
    <h1 class="text-4xl font-extrabold text-gray-900 mb-1"><%= @quiz.title %></h1>
    <p class="text-lg text-gray-500"><%= @quiz.description %></p>
  </div> 
  <div> 
    <%= link_to 'Start Quiz', new_quiz_quiz_session_path(quiz_id: @quiz.id) %>
  </div> 
</div>