config/routes.rb
Rails.application.routes.draw do

  resources :quiz_sessions do
    member do
      get 'start'
    end
    resources :answers, only: [:create]
  end

  resources :answers, only: [:create]

  resources :questions do
    member do
      patch :toggle_status
    end
  end

  resources :quizzes do
    resources :questions
    resources :quiz_sessions
    member do
      post :add_questions
    end
  end

  devise_for :users

  authenticated :user do
    root 'quizzes#index', as: :authenticated_root
  end

  root "quizzes#index"

  resources :entries

  resources :children do
    resources :entries, only: [:create, :destroy, :new, :show, :edit, :update]
  end

  resources :users do
    resources :children
  end
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :quiz_session
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/child.rb
class Child < ApplicationRecord
  attr_accessor :quiz_id, :from_quiz_session

  belongs_to :user
  has_many :quiz_sessions, dependent: :destroy
  has_many :entries, dependent: :destroy

  after_create :create_quiz_session

  def create_quiz_session
    QuizSession.create(child_id: self.id, quiz_id: self.quiz_id) if self.quiz_id.present?
  end
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :child
  belongs_to :prompt

  has_rich_text :response
end

app/models/prompt.rb
class Prompt < ApplicationRecord
  has_many :entries
end

app/models/question.rb
class Question < ApplicationRecord
  serialize :options, Array, coder: JSON

  has_many :quiz_questions, dependent: :destroy
  has_many :quizzes, through: :quiz_questions

  has_rich_text :text

  enum status: { inactive: "inactive", active: "active" }
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  has_many :quiz_questions, dependent: :destroy
  has_many :questions, through: :quiz_questions
  has_many :quiz_sessions, dependent: :destroy

  accepts_nested_attributes_for :questions, allow_destroy: true

  enum status: { draft: 'draft', active: 'active', another_status: 'another_status' }
end

app/models/quiz_question.rb
class QuizQuestion < ApplicationRecord
  belongs_to :quiz
  belongs_to :question
end

app/models/quiz_session.rb
class QuizSession < ApplicationRecord
  belongs_to :child
  belongs_to :quiz
  has_many :answers

  accepts_nested_attributes_for :child


  def next_question
    # Simple example: Get the next question by sequence that hasn't been answered yet
    answered_question_ids = self.answers.pluck(:question_id)
    self.quiz.questions.where.not(id: answered_question_ids).order(:sequence_number).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :children

  accepts_nested_attributes_for :children, allow_destroy: true

  enum role: [:user, :admin]
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    @answer = Answer.new(answer_params)
    @answer.question_id = params[:answer][:question_id]
    @answer.quiz_session_id = params[:answer][:quiz_session_id]

    if @answer.save
      next_question = @answer.quiz_session.next_question

      if next_question
        redirect_to action: :start, controller: 'quiz_sessions', id: @answer.quiz_session_id, notice: 'Your answer was successfully recorded.'
      else
        redirect_to quiz_completion_path(@answer.quiz_session), notice: 'Quiz completed!'
      end
    else
      render 'questions/show', status: :unprocessable_entity
    end
  end

  private
  def answer_params
    params.require(:answer).permit(:options, :question_id, :quiz_session_id, :text, :user_id, :selected_option)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /users or /users.json
  def index
    @users = User.all
    authorize @users
  end

  # GET /users/1 or /users/1.json
  def show
    @user = params[:id] ? User.find(params[:id]) : current_user
    @my_children = current_user.children
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = params[:id] ? User.find(params[:id]) : current_user
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quiz_sessions_helper.rb
module QuizSessionsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Momentos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <span class=""><%= notice %></span>
    <span class=""><%= alert %></span>

    <main class="container mx-auto px-5">
      <% if user_signed_in? && current_user.admin? %>
        <%= render 'shared/admin_navbar' %>
      <% else %>
        <%= render 'shared/navbar' %>
      <% end %>
      
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_admin_navbar.html.erb
<div class="navbar bg-base-100">
  <div class="flex-1">
    <%= link_to 'Mementos', root_path , class:'btn btn-ghost text-xl' %>
  </div>
  <div class="flex-none">
    <ul class="menu menu-horizontal px-1">
      <% if user_signed_in? %>
        <li>
          <%= link_to 'User', user_path(current_user) , class:'block px-4 py-2 text-sm text-gray-700'%>
        </li>
        <li>
          <%= link_to 'New Quiz', new_quiz_path , class:'block px-4 py-2 text-sm text-gray-700'%>
        </li>
        <li>
          <%= link_to 'All Quizes', quizzes_path, class:'block px-4 py-2 text-sm text-gray-700' %>
        </li>
        <li>
          <%= link_to 'Create Question', new_question_path , class:'block px-4 py-2 text-sm text-gray-700'%>
        </li>
        <li>
          <%= link_to 'All Questions', questions_path , class:'block px-4 py-2 text-sm text-gray-700'%>
        </li>
        <li>
          <%= link_to "Sign out", destroy_user_session_path, class:'block px-4 py-2 text-sm text-gray-700', data:{turbo_method: :delete} %>
        </li>
      <% else %>
          <%= link_to 'Sign in', new_user_session_path , class:'block px-4 py-2 text-sm text-gray-700'%>
      <% end %>
      <li>
        <details>
          <summary>
            Parent
          </summary>
          <ul class="p-2 bg-base-100 rounded-t-none">
            <li> <%= link_to 'User', user_path(current_user) , class:'block px-4 py-2 text-sm text-gray-700' if user_signed_in? %></li>
            <li>
              <% if user_signed_in? %>
                <%= link_to "Log out", destroy_user_session_path, class:'block px-4 py-2 text-sm text-gray-700', data:{turbo_method: :delete} %>
              <% else %>
                <%= link_to 'Log in', new_user_session_path , class:'block px-4 py-2 text-sm text-gray-700'%>
              <% end %>
            </li>
          </ul>
        </details>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar bg-base-100">
  <div class="flex-1">
    <%= link_to 'Mementos', root_path , class:'btn btn-ghost text-xl' %>
  </div>
  <div class="flex-none">
    <ul class="menu menu-horizontal px-1">
      <li>
        <%= link_to 'All Quizzes', quizzes_path, class:'block px-4 py-2 text-sm text-gray-700' %>
      </li>
      <li>
        <details>
          <summary>
            Profile
          </summary>
          <ul class="p-2 bg-base-100 rounded-t-none">
            <li> <%= link_to 'User', user_path(current_user) , class:'block px-4 py-2 text-sm text-gray-700' if user_signed_in? %></li>
            <li>
              <% if user_signed_in? %>
                <%= link_to "Log out", destroy_user_session_path, class:'block px-4 py-2 text-sm text-gray-700', data:{turbo_method: :delete} %>
              <% else %>
                <%= link_to 'Log in', new_user_session_path , class:'block px-4 py-2 text-sm text-gray-700'%>
              <% end %>
            </li>
          </ul>
        </details>
      </li>
    </ul>
  </div>
</div>